mlflow_directory: ./mlflow/

text:
  text_model_name: "bert-base-uncased"
  num_words: 100

image:
  image_model_name: "openai/clip-vit-base-patch32"

video:
  duration: 5
  video_model_name: "microsoft/xclip-base-patch32"
