defaults:
  - _self_
  - agent/image_agent@image_agent
  - agent/modality_agent@modality_agent
  - agent/paraphrase_agent@paraphrase_agent
  - agent/text_agent@text_agent
  - agent/video_agent@video_agent
  - evaluation/evaluation@evaluation

model: gemini-2.5-pro
temperature: 1.0
moderation_model: omni-moderation-latest
output_path: ./data/
evaluate: True