defaults:
  - _self_
  - agent/image_agent@image_agent
  - agent/modality_agent@modality_agent
  - agent/paraphrase_agent@paraphrase_agent
  - agent/text_agent@text_agent
  - agent/video_agent@video_agent
  - evaluation/evaluation@evaluation

model: gemini-2.5-pro
temperature: 1.5
moderation_model: omni-moderation-latest
questions: "./data/questions/queries.txt"
evaluate: True
gradio:
  caption: "OmniAnswer: Ask any question. I determine the best explanation mode â€” text, visuals, or structured examples."