name: OmniAnswer CI-CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {} 

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt')}}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r dev-requirements.txt

      - name: Pre-commit Hooks
        run: pre-commit run --all-files

      - name: Run Unit Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest -q

      - name: Build Docker Image
        run: | 
          docker build -t omnianswer:${{ github.sha }} \
          -f docker/omnianswer.Dockerfile \
          .
      
      - name: Test Docker Image
        run: | 
          docker run --rm --user root \
          -v "${{ github.workspace }}:/home/omnianswer" \
          -e PYTHONPATH="/home/omnianswer:/home/omnianswer/src" \
          "omnianswer:${{ github.sha }}" \
          pytest -q tests

  trigger-codebuild:
    needs: ci-pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Trigger AWS CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with: 
          project-name: omnianswer-build
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID  }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}